name: Pipelineworkflow

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master


jobs:
  build:
      name: Azure Pipeline
      runs-on: ubuntu-latest
      steps:
      - name: Azure Pipelines Action
        user: Azure/pipeline@v1
        with:
          azure-devops-projecy-url: https://dev.azure.com/zuber1234567890/AgileProject
          azure-pipeline-name: 'ajiteshsharma90.Gitapp'
          azure-devops-token: ${{secret.AZURE_DEVOPS_TOKEN}}